"""Output-column contract for urban-renewal prediction rows."""

from __future__ import annotations

from typing import Any

from ...runtime.config import Schema
from ..dynamic.topic_discovery import DYNAMIC_BINARY_DEFAULTS, DYNAMIC_TOPIC_DEFAULTS
from ..hybrid.binary_policy_v2 import BINARY_POLICY_V2_DEFAULTS
from ..strategy import STRATEGY_V3_DEFAULTS


EXPLAINABILITY_DEFAULTS: dict[str, Any] = {
    "decision_explanation": "",
    "primary_positive_evidence": "",
    "primary_negative_evidence": "",
    "evidence_balance": "",
    "decision_rule_stack": "",
    "binary_decision_evidence": "",
    "urban_probability_score": "",
    "binary_decision_threshold": "",
    "binary_decision_source": "",
    "taxonomy_coverage_status": "",
    "unknown_recovery_path": "",
    "unknown_recovery_evidence": "",
}

DYNAMIC_TOPIC_DEFAULTS_FOR_OUTPUT: dict[str, Any] = dict(DYNAMIC_TOPIC_DEFAULTS)
DYNAMIC_BINARY_DEFAULTS_FOR_OUTPUT: dict[str, Any] = dict(DYNAMIC_BINARY_DEFAULTS)
BINARY_POLICY_V2_DEFAULTS_FOR_OUTPUT: dict[str, Any] = dict(BINARY_POLICY_V2_DEFAULTS)
STRATEGY_V3_DEFAULTS_FOR_OUTPUT: dict[str, Any] = dict(STRATEGY_V3_DEFAULTS)

URBAN_RESULT_COLUMNS = [
    "final_label",
    "confidence",
    "metadata_route",
    "metadata_route_reason",
    "metadata_candidate_topic_buckets",
    "metadata_candidate_matches",
    "llm_used",
    "llm_attempted",
    "llm_failure_reason",
    Schema.AUTHOR_KEYWORDS,
    Schema.KEYWORDS_PLUS,
    Schema.KEYWORDS,
    Schema.WOS_CATEGORIES,
    Schema.RESEARCH_AREAS,
    "metadata_filter_result",
    "metadata_filter_reason",
    "metadata_positive_signals",
    "stage1_decision",
    "stage1_reason_tag",
    "stage1_hit_signals",
    "stage1_risk_tags",
    "stage1_conflict_flag",
    "metadata_negative_domains",
    "metadata_negative_keywords",
    "metadata_related_domains",
    "topic_rule",
    "topic_rule_group",
    "topic_rule_name",
    "topic_rule_score",
    "topic_rule_margin",
    "topic_rule_top3",
    "topic_rule_matches",
    "review_flag_rule",
    "review_reason_rule",
    "review_flag",
    "review_reason",
    "llm_family_hint",
    "llm_family_hint_reason",
    "legacy_topic_label",
    "legacy_topic_group",
    "legacy_topic_name",
    "topic_local_label",
    "topic_local_group",
    "topic_local_name",
    "topic_local_confidence",
    "topic_local_margin",
    "topic_local_top3",
    "topic_final",
    "topic_final_group",
    "topic_final_name",
    "topic_label",
    "topic_group",
    "topic_name",
    "topic_confidence",
    "topic_margin",
    "topic_confidence_effective",
    "topic_margin_effective",
    "topic_matches",
    "topic_binary_score",
    "topic_binary_probability",
    "bertopic_status",
    "bertopic_topic_id",
    "bertopic_topic_name",
    "bertopic_probability",
    "bertopic_is_outlier",
    "bertopic_count",
    "bertopic_pos_rate",
    "bertopic_mapped_label",
    "bertopic_mapped_group",
    "bertopic_mapped_name",
    "bertopic_label_purity",
    "bertopic_mapped_label_share",
    "bertopic_top_terms",
    "bertopic_sample_titles",
    "bertopic_source_split",
    "bertopic_high_purity",
    "bertopic_true_outlier",
    "bertopic_prior_mode",
    "bertopic_confidence_delta",
    "bertopic_margin_delta",
    "bertopic_hint_label",
    "bertopic_hint_group",
    "bertopic_hint_name",
    "bertopic_hint_conflict_flag",
    "bertopic_cluster_quality",
    "bertopic_dynamic_topic_id",
    "bertopic_dynamic_topic_words",
    "bertopic_primary_label",
    "bertopic_primary_group",
    "bertopic_primary_name",
    "bertopic_primary_probability",
    "bertopic_primary_support",
    "bertopic_primary_purity",
    "bertopic_primary_mapped_share",
    "bertopic_primary_override",
    "bertopic_primary_reason",
    "topic_family_rule",
    "topic_family_local",
    "topic_family_final",
    "family_predicted_family",
    "family_decision_source",
    "family_confidence",
    "family_probability_urban",
    "topic_within_family_label",
    "topic_family_within_score",
    "topic_family_within_margin",
    "boundary_bucket",
    "family_conflict_pattern",
    "unknown_recovery_path",
    "unknown_recovery_evidence",
    "anchor_guard_flag",
    "anchor_guard_action",
    "anchor_guard_reason",
    "anchor_guard_hits",
    "uncertain_nonurban_guard_flag",
    "uncertain_nonurban_guard_action",
    "uncertain_nonurban_guard_reason",
    "uncertain_nonurban_guard_evidence",
    "urban_probability_score",
    "binary_decision_threshold",
    "binary_decision_source",
    "binary_decision_evidence",
    "binary_topic_consistency_flag",
    "binary_recall_calibration_flag",
    "binary_recall_calibration_tier",
    "binary_recall_calibration_reason",
    "binary_audit_resolution_flag",
    "binary_audit_resolution_action",
    "binary_audit_resolution_reason",
    "binary_audit_resolution_evidence",
    "review_flag_raw",
    "review_reason_raw",
    "open_set_flag",
    "open_set_topic",
    "open_set_reason",
    "open_set_evidence",
    "taxonomy_coverage_status",
    "decision_explanation",
    "primary_positive_evidence",
    "primary_negative_evidence",
    "evidence_balance",
    "decision_rule_stack",
    "dynamic_topic_id",
    "dynamic_topic_name_zh",
    "dynamic_topic_keywords",
    "dynamic_topic_size",
    "dynamic_topic_confidence",
    "dynamic_topic_source_pool",
    "dynamic_to_fixed_topic_candidate",
    "dynamic_mapping_status",
    "dynamic_binary_candidate_label",
    "dynamic_binary_candidate_confidence",
    "dynamic_binary_candidate_action",
    "dynamic_binary_candidate_reason",
    "dynamic_binary_review_priority",
    "dynamic_binary_override_applied",
    "dynamic_binary_override_label",
    "dynamic_binary_override_topic",
    "dynamic_binary_override_reason",
    "dynamic_binary_override_source",
    "binary_policy_action",
    "binary_policy_reason",
    "binary_policy_conflict_type",
    "llm_adjudication_required",
    "llm_adjudication_label",
    "llm_adjudication_confidence",
    "llm_adjudication_reason",
    "strategy_v3_label",
    "strategy_v3_topic",
    "strategy_v3_status",
    "strategy_v3_reason",
    "strategy_v3_evidence",
    "strategy_v3_confidence",
    "decision_source",
    "decision_reason",
]

OUTPUT_DEFAULT_GROUPS = (
    EXPLAINABILITY_DEFAULTS,
    DYNAMIC_TOPIC_DEFAULTS_FOR_OUTPUT,
    DYNAMIC_BINARY_DEFAULTS_FOR_OUTPUT,
    BINARY_POLICY_V2_DEFAULTS_FOR_OUTPUT,
    STRATEGY_V3_DEFAULTS_FOR_OUTPUT,
)


def apply_urban_output_defaults(row: dict[str, Any]) -> dict[str, Any]:
    """Fill optional urban-renewal output columns with contract defaults."""

    for defaults in OUTPUT_DEFAULT_GROUPS:
        for column, default_value in defaults.items():
            row.setdefault(column, default_value)
    return row
